services:
  - type: web
    name: pay-bot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CRYPTO_PAY_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: CRYPTO_ASSET
        value: USDT
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false